# Generated by Django 3.0.4 on 2020-03-22 10:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedMovieItem',
            fields=[
                ('id', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 3, 22, 10, 28, 26, 211939, tzinfo=utc))),
            ],
        ),
    ]
