# Generated by Django 3.0.4 on 2020-03-22 10:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedmovieitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 10, 32, 43, 662256, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scrapedmovieitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
