# Generated by Django 3.0.4 on 2020-03-22 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_scraping', '0002_auto_20200322_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceURL',
            fields=[
                ('site_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='scrapedmovieitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 22, 10, 41, 22, 761249, tzinfo=utc)),
        ),
    ]
