# Generated by Django 3.0.4 on 2020-03-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_scraping', '0003_auto_20200322_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField()),
                ('day_of_week', models.CharField(max_length=3)),
                ('day_of_month', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ScrapedMovieItem',
        ),
    ]
