# Generated by Django 3.0.4 on 2020-03-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('rating', models.PositiveSmallIntegerField()),
                ('review_number', models.CharField(max_length=20)),
            ],
        ),
    ]
